# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8081

spring:
  mvc:
    async:
      #设置API超时时间
      request-timeout: 600000

openAi:
#accessToken
  accessToken: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1UaEVOVUpHTkVNMVFURTRNMEZCTWpkQ05UZzVNRFUxUlRVd1FVSkRNRU13UmtGRVFrRXpSZyJ9.eyJodHRwczovL2FwaS5vcGVuYWkuY29tL3Byb2ZpbGUiOnsiZW1haWwiOiJ2NjVneGRkMnpqQHByaXZhdGVyZWxheS5hcHBsZWlkLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlfSwiaHR0cHM6Ly9hcGkub3BlbmFpLmNvbS9hdXRoIjp7InVzZXJfaWQiOiJ1c2VyLXVkWGlFTWwwb29FSHE0N0VaWVhmdG5lWiJ9LCJpc3MiOiJodHRwczovL2F1dGgwLm9wZW5haS5jb20vIiwic3ViIjoiYXBwbGV8MDAxNjQ5LmYyZDIwYjY3OTJhYjRjZTY5N2U0OGU5NGUyZTJkOTZlLjA5MDMiLCJhdWQiOlsiaHR0cHM6Ly9hcGkub3BlbmFpLmNvbS92MSIsImh0dHBzOi8vb3BlbmFpLm9wZW5haS5hdXRoMGFwcC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNjkwNzg2NDg5LCJleHAiOjE2OTE5OTYwODksImF6cCI6IlRkSkljYmUxNldvVEh0Tjk1bnl5d2g1RTR5T282SXRHIiwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCBtb2RlbC5yZWFkIG1vZGVsLnJlcXVlc3Qgb3JnYW5pemF0aW9uLnJlYWQgb3JnYW5pemF0aW9uLndyaXRlIG9mZmxpbmVfYWNjZXNzIn0.E2NOPyut6MITDkfUxvujIsYKvbj6E-ugzuvGMxVF4QxiUg8JgCJXdMJCvmyLc4AoyNZ0N7jYMKWM64rOLqglOndWPKidP7nPTwJWz5qbH1fSWBpsrV6C77z9j9yHkPzqLqc-D1QMhpA0hK_m6xni8JuewyEdSgNVEBXdtK2oyLxJ_v_IsD5MyU9DP1SaMdW6SG97kpJ_meQmu_BIpQEi2IY2CXBXPPqMGuJk-GAhOvBAUos1_yJqnv0tgN64IfS6MQhmeyDtTz-gCBFtaymLwv1jRK09iNyFTBTz7iHbaZoQhg7s6SZpadV002gIwEX9rshc9g62GLzquR0KgWUULA
#proxyHost
  proxyHost: 127.0.0.1
#proxyPort
  proxyPort: 7891